# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:              Paleomedia
tagline:            'Nathaniel Hoffman".s digital repository'
description:        'Journalist, author of @amorandexile, Paleomedia curator, @reviewblue editor, estudent, sometimes hunter/gatherer'
url:                http://paleomedia.github.io/
baseurl:            ''
paginate:           5

# About/contact
author:
  name:              Nathaniel Hoffman
  url:               https://twitter.com/paleomedia
  email:             nathaniel.hoffman@gmail.com

# Custom vars
version:             1.0.0
